default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: truyencuoi
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

test:
  <<: *default
  database: truyencuoi_test
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

# Heroku provides DATABASE_URL, which is merged into this config.
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
